/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.uniska.pbo2.p03;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class FormTiketTravel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTiketTravel.class.getName());

    /**
     * Creates new form FormTiketTravel
     */
    public FormTiketTravel() {
        initComponents();
        namaField.putClientProperty("JTextField.placeholderText", "Nama sesuai KTP");
        hpField.putClientProperty("JTextField.placeholderText", "08xxxxxxxxxx");
        getRootPane().setDefaultButton(pesanButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kelasGroup = new javax.swing.ButtonGroup();
        namaLabel = new javax.swing.JLabel();
        hpLabel = new javax.swing.JLabel();
        kotaLabel = new javax.swing.JLabel();
        kelasLabel = new javax.swing.JLabel();
        fasilitasLabel = new javax.swing.JLabel();
        catatanLabel = new javax.swing.JLabel();
        temaToggle = new javax.swing.JToggleButton();
        pesanButton = new javax.swing.JButton();
        namaField = new javax.swing.JTextField();
        hpField = new javax.swing.JTextField();
        kotaCombo = new javax.swing.JComboBox<>();
        ekonomiRadio = new javax.swing.JRadioButton();
        bisnisRadio = new javax.swing.JRadioButton();
        eksekutifRadio = new javax.swing.JRadioButton();
        bagasiCheck = new javax.swing.JCheckBox();
        makanCheck = new javax.swing.JCheckBox();
        asuransiCheck = new javax.swing.JCheckBox();
        catatanScroll = new javax.swing.JScrollPane();
        catatanArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Pemesanan Tiket Travel");

        namaLabel.setText("Nama Pemesan");

        hpLabel.setText("Nomor HP");

        kotaLabel.setText("Kota Tujuan");

        kelasLabel.setText("Kelas");

        fasilitasLabel.setText("Fasilitas Tambahan");

        catatanLabel.setText("Catatan");

        temaToggle.setText("Mode Gelap");
        temaToggle.addActionListener(this::temaToggleActionPerformed);

        pesanButton.setText("Pesan");
        pesanButton.addActionListener(this::pesanButtonActionPerformed);

        hpField.addActionListener(this::hpFieldActionPerformed);

        kotaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banjarbaru", "Martapura", "Palangka Raya", "Samarinda", "Balikpapan" }));

        kelasGroup.add(ekonomiRadio);
        ekonomiRadio.setSelected(true);
        ekonomiRadio.setText("Ekonomi");

        kelasGroup.add(bisnisRadio);
        bisnisRadio.setText("Bisnis");
        bisnisRadio.addActionListener(this::bisnisRadioActionPerformed);

        kelasGroup.add(eksekutifRadio);
        eksekutifRadio.setText("Eksekutif");

        bagasiCheck.setText("Bagasi");

        makanCheck.setText("Makan");

        asuransiCheck.setText("Asuransi");

        catatanArea.setColumns(20);
        catatanArea.setRows(3);
        catatanScroll.setViewportView(catatanArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaLabel)
                    .addComponent(hpLabel)
                    .addComponent(kotaLabel)
                    .addComponent(kelasLabel)
                    .addComponent(fasilitasLabel)
                    .addComponent(catatanLabel))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bagasiCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ekonomiRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addComponent(makanCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(asuransiCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addComponent(bisnisRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(eksekutifRadio)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(temaToggle)
                                .addGap(18, 18, 18)
                                .addComponent(pesanButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(namaField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(hpField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(kotaCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 232, Short.MAX_VALUE))
                            .addComponent(catatanScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaLabel)
                    .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hpLabel)
                    .addComponent(hpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kotaLabel)
                    .addComponent(kotaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kelasLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ekonomiRadio)
                        .addComponent(bisnisRadio)
                        .addComponent(eksekutifRadio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fasilitasLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bagasiCheck)
                        .addComponent(makanCheck)
                        .addComponent(asuransiCheck)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(catatanLabel)
                    .addComponent(catatanScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temaToggle)
                    .addComponent(pesanButton))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bisnisRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bisnisRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bisnisRadioActionPerformed

    private void hpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hpFieldActionPerformed

    private void pesanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanButtonActionPerformed
        tampilkanRingkasan();
    }//GEN-LAST:event_pesanButtonActionPerformed

    private void temaToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temaToggleActionPerformed
        gantiTema(temaToggle.isSelected());
    }//GEN-LAST:event_temaToggleActionPerformed

    /**
     * @param args the command line arguments
     */
        private void tampilkanRingkasan() {
        String kelas = "Ekonomi";
        if (bisnisRadio.isSelected()) {
            kelas = "Bisnis";
        } else if (eksekutifRadio.isSelected()) {
            kelas = "Eksekutif";
        }

        List<String> fasilitas = new ArrayList<>();
        for (JCheckBox cb : List.of(bagasiCheck, makanCheck, asuransiCheck)) {
            if (cb.isSelected()) {
                fasilitas.add(cb.getText());
            }
        }

        String catatan = catatanArea.getText().isBlank() ? "-" : catatanArea.getText();

        String pesan = "Nama Pemesan: " + namaField.getText()
                + "\nNomor HP: " + hpField.getText()
                + "\nKota Tujuan: " + kotaCombo.getSelectedItem()
                + "\nKelas: " + kelas
                + "\nFasilitas: " + (fasilitas.isEmpty() ? "-" : String.join(", ", fasilitas))
                + "\nCatatan: " + catatan;
        JOptionPane.showMessageDialog(this, pesan, "Data Pemesanan",
                JOptionPane.INFORMATION_MESSAGE);
    }

    private void gantiTema(boolean gelap) {
        if (gelap) {
            FlatDarkLaf.setup();
        } else {
            FlatLightLaf.setup();
        }
        FlatLaf.updateUI();
        temaToggle.setText(gelap ? "Mode Terang" : "Mode Gelap");
    }

    public static void main(String args[]) {
        FlatLightLaf.setup();

        java.awt.EventQueue.invokeLater(() -> new FormTiketTravel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox asuransiCheck;
    private javax.swing.JCheckBox bagasiCheck;
    private javax.swing.JRadioButton bisnisRadio;
    private javax.swing.JTextArea catatanArea;
    private javax.swing.JLabel catatanLabel;
    private javax.swing.JScrollPane catatanScroll;
    private javax.swing.JRadioButton ekonomiRadio;
    private javax.swing.JRadioButton eksekutifRadio;
    private javax.swing.JLabel fasilitasLabel;
    private javax.swing.JTextField hpField;
    private javax.swing.JLabel hpLabel;
    private javax.swing.ButtonGroup kelasGroup;
    private javax.swing.JLabel kelasLabel;
    private javax.swing.JComboBox<String> kotaCombo;
    private javax.swing.JLabel kotaLabel;
    private javax.swing.JCheckBox makanCheck;
    private javax.swing.JTextField namaField;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JButton pesanButton;
    private javax.swing.JToggleButton temaToggle;
    // End of variables declaration//GEN-END:variables
}
